---
titlg: "Seal_Carrion_analysis"
author: "Neil Burns"
datg: "17 March 2022"
output: html_document
editor_options: 
  chunk_output_typg: console
  chunk_output_type: console
---


```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)

library(lme4)
library(merTools)
library(DescTools)
library(RColorBrewer)


# dat.pa load  'All_carcass_pres_abs.csv'
# dat.dur load  'carcass_data_duration.csv'
# dat.tide load 'tide2012_2008R.csv'

```


# general setup & covariance checkes
```{r}
###data tidy###
dat.pa$location<- factor(dat.pa$location)
dat.pa$year<- factor(dat.pa$year)
## create more appropriate variable for "displaced to marine"
t<- dplyr::count(dat.pa, year, rev_pres, name='number')
t

# test for co-linearity - VIF code available in Zuur - 2009. ref in manuscript text
co.mod1 <- glm(rev_pres ~ location + dist + elev + vector +year, family = binomial, data=dat.pa)
vif(co.mod1) #all are under 3 so can look at all variables

co.mod1 <- glm(rev_pres ~ location + dist + elev +year, family = binomial, data=dat.pa)
vif(co.mod1) #all are under 3 so can look at all variables



```


#Kovacs & Lavigne equations for reference
```{r}

### 3 age categories used
a1<- (2+5)/2
a2<- 12
a3<- 18

### m.m= male mass, f.m = female mass
m.m<- (1.39*a1)+16.33

f.m<- (1.25*a1)+14.57

m1<- (m.m+f.m)/2
m1
##################
m.m<- (1.39*a2)+16.33

f.m<- (1.25*a2)+14.57

m2<- (m.m+f.m)/2
m2
#####################
m.m<- (1.39*a3)+16.33

f.m<- (1.25*a3)+14.57

m3<- (m.m+f.m)/2
m3


## Mean mass for combined developmental stages from Quaggiotto 2018 for "minimum" values
d1<- (9.6+11.7)/2
d1
d2<- (21.6+15)/2
d2
d1_2<- (d1+d2)/2
d1_2

d3<- (21.7+25.1)/2
d3
d4<- (32.6+36.1)/2
d4
d5<- (28.8+33.2)/2
d4_5<- (d4+d5)/2
d4_5
```


#Tides and plots
```{r}

### Tide data tidy #######
head(dat.tide)
dat.tide<- dat.tide[,c(1:2)]

tide08<- subset(dat.tide, dat.tide$Year==2008)
tide12<- subset(dat.tide, dat.tide$Year==2012)
head(tide08)

max(tide08$height.corrected.for.chart)
min(tide08$height.corrected.for.chart)


d1<- as.Date("18/10/08", "%d/%m/%y")
d2<- as.Date("30/11/08", "%d/%m/%y")
d1-d2

dry<- data.frame('x'= c(-60, -60, nrow(tide08), nrow(tide08)), 'y'=c(5.37, 6, 6, 5.37))
HWN_HWS<- data.frame('x'= c(-60, -60, nrow(tide08), nrow(tide08)), 'y'=c(3.6, 5.37, 5.37, 3.6))
LWN_HWN<- data.frame('x'= c(-60, -60, nrow(tide08), nrow(tide08)), 'y'=c(1.51, 3.60, 3.60, 1.51))
LWS_LWN<- data.frame('x'= c(-60, -60, nrow(tide08), nrow(tide08)), 'y'=c(-0.07, 1.51, 1.51, -0.07))



tide.shades<- brewer.pal(11,'RdYlBu')

#####Plot 1####
par(mar=c(1,1,0,0)+0.1)
par(xpd=F)

plot(tide08[,1], type ='n', axes=FALSE, xlab= NA, ylab=NA, lwd=1.5, ylim=c(0,6))
polygon(dry, col=SetAlpha(tide.shades[4], 0.2), border=NA)
polygon(HWN_HWS, col=SetAlpha(tide.shades[5], 0.3), border=NA)
polygon(LWN_HWN, col=SetAlpha(tide.shades[9], 0.3), border=NA)
polygon(LWS_LWN, col=SetAlpha(tide.shades[10], 0.3), border=NA)



segments(-60, 5.37, nrow(tide08),  5.37, col='grey70', lwd=1)
segments(-60, 3.6, nrow(tide08),  3.6, col='grey70', lwd=1)
segments(-60, 1.51, nrow(tide08),  1.51, col='grey70', lwd=1)

lines(tide08[,1], lwd=1)
axis(1, at = seq(from=0, to=nrow(tide08),length.out = 44), labels= FALSE, pos= -0.1)
axis(2, at =  c('0','1', '2', '3', '4', '5', '6'), line=-0.9, labels=c('0','1', '2', '3', '4', '5', '6'))

segments(-60, 4.68, nrow(tide08),  4.68, col='dodgerblue4', lwd=2)
segments(-60, 2.99, nrow(tide08),  2.99, col='dodgerblue4', lwd=2)


####Plot 2#####
max(tide12$height.corrected.for.chart)
min(tide12$height.corrected.for.chart)


d1<- as.Date("14/10/12", "%d/%m/%y")
d2<- as.Date("28/11/12", "%d/%m/%y")
d1-d2



dry<- data.frame('x'= c(-60, -60, nrow(tide12), nrow(tide12)), 'y'=c(5.36, 6, 6, 5.36))
HWN_HWS<- data.frame('x'= c(-60, -60, nrow(tide12), nrow(tide12)), 'y'=c(3.99, 5.36, 5.36, 3.99))
LWN_HWN<- data.frame('x'= c(-60, -60, nrow(tide12), nrow(tide12)), 'y'=c(1.50, 3.99, 3.99, 1.50))
LWS_LWN<- data.frame('x'= c(-60, -60, nrow(tide12), nrow(tide12)), 'y'=c(-0.06, 1.50, 1.50, -0.06))


par(mar=c(1,1,0,0)+0.1)
par(xpd=F)

plot(tide12[,1], type ='n', axes=FALSE, xlab= NA, ylab=NA, lwd=1.5, ylim=c(0,6))

polygon(dry, col=SetAlpha(tide.shades[4], 0.2), border=NA)
polygon(HWN_HWS, col=SetAlpha(tide.shades[5], 0.3), border=NA)
polygon(LWN_HWN, col=SetAlpha(tide.shades[9], 0.3), border=NA)
polygon(LWS_LWN, col=SetAlpha(tide.shades[10], 0.3), border=NA)


segments(-60, 5.36, nrow(tide12), 5.36, col='grey70', lwd=1)
segments(-60, 3.99, nrow(tide12), 3.99, col='grey70', lwd=1)
segments(-60, 1.50, nrow(tide12), 1.50, col='grey70', lwd=1)

lines(tide12[,1], lwd=1)

axis(1, at = seq(from=0, to=nrow(tide12),length.out = 46), labels= FALSE, pos= -0.1)
axis(2, at =  c('0','1', '2', '3', '4', '5', '6'), line=-0.9, labels=c('0','1', '2', '3', '4', '5', '6'))

segments(-60, 4.64, nrow(tide12), 4.64, col='dodgerblue4', lwd=2)
segments(-60, 3.5, nrow(tide12), 3.5, col='dodgerblue4', lwd=2)

```

#GLMM analysis - Probability of carcass being displaced to marine
```{r}

m.mod1a<-glmer(rev_pres ~ location + vector+ location:vector+
             (1|year), data=dat.pa, family = binomial) 
summary(m.mod1a)

m.mod2a<-glmer(rev_pres ~ location + vector+ 
             (1|year), data=dat.pa, family = binomial)

AIC(m.mod1a, m.mod2a) ### optimal model going forward is m.mod1a


```

#plot model predictions
```{r}

new.dat<- data.frame(expand.grid('location'=levels(dat.pa$location),'vector'=seq(min(dat.pa$vector), max(dat.pa$vector), by=0.1),'year'=c('2008','2012') )    )


intFit.p <- predictInterval(m.mod1a, newdata = new.dat, stat='median', level=0.95, type = "probability", n.sims=999, which = 'fixed')
 
pred.dat<- cbind(new.dat, intFit.p)




### subset for the effect in E.Tarbet and do ech area - plots show "central" trend and the 95% CI from 1000 simulations (fitted with a smoother)
ET.dat8<- subset(pred.dat, pred.dat$location=='E.Tarbet' & pred.dat$year=='2008') ## here we use 2008 to prevent double plotting but it does not matter if its 2008 or 2012 as we are plotting the central tendency 
fit.loET8<- loess(fit ~ vector, data= ET.dat8, span=0.1)
upr.lo.ET8<- loess(upr ~ vector, data= ET.dat8, span=0.2)
lwr.lo.ET8<- loess(lwr ~ vector, data= ET.dat8, span=0.2)
##make upper and lower into polygon
poly.ET<- data.frame('x'=c(ET.dat8$vector,rev(ET.dat8$vector)), 'y'= c(predict(upr.lo.ET8), rev(predict(lwr.lo.ET8))))

P.dat8<- subset(pred.dat, pred.dat$location=='Pilgrims' & pred.dat$year=='2008')
fit.loP8<- loess(fit ~ vector, data= P.dat8, span=0.1)
upr.lo.P8<- loess(upr ~ vector, data= P.dat8, span=0.2)
lwr.lo.P8<- loess(lwr ~ vector, data= P.dat8, span=0.2)
##make upper and lower into polygon
poly.P<- data.frame('x'=c(P.dat8$vector,rev(P.dat8$vector)), 'y'= c(predict(upr.lo.P8), rev(predict(lwr.lo.P8))))

L.dat8<- subset(pred.dat, pred.dat$location=='The_Loan'& pred.dat$year=='2008')
fit.loL8<- loess(fit ~ vector, data= L.dat8, span=0.1)
upr.lo.L8<- loess(upr ~ vector, data= L.dat8, span=0.2)
lwr.lo.L8<- loess(lwr ~ vector, data= L.dat8, span=0.2)
##make upper and lower into polygon
poly.L<- data.frame('x'=c(L.dat8$vector,rev(L.dat8$vector)), 'y'= c(predict(upr.lo.L8), rev(predict(lwr.lo.L8))))



par(mar=c(4,4,0,0)+0.1)

plot(dat.pa$vector, dat.pa$rev_pres,  xlim=c(0,420), ylim=c(0,1), pch=16, ylab='Probability of carcass disappearance', xlab='Distance from shore (vector; m)')
polygon(poly.ET, col=SetAlpha("cadetblue", 0.4), border=NA)

polygon(poly.P, col=SetAlpha("firebrick", 0.4), border=NA)
polygon(poly.L, col=SetAlpha("goldenrod1", 0.3), border=NA)

lines(predict(fit.loET8)~ vector, data= ET.dat8, lty=1,   col='cadetblue', lwd=2)
lines(predict(fit.loL8)~ vector, data= L.dat8, lty=1,   col='yellow', lwd=2)

lines(predict(fit.loP8)~ vector, data= P.dat8, lty=1,   col='firebrick', lwd=2)


```


#duration analysis
```{r}

# data tidy

str(dat.dur)
dat.dur$Year<- as.factor(dat.dur$Year)
dat.dur$area<- as.factor(dat.dur$area)
dat.dur$tide_strata<- as.factor(dat.dur$tide_strata)
summary(dat.dur$tide_strata)

dat.dur$ID_gone<- as.factor(dat.dur$ID_gone)
dat.dur$arrival<- as.Date(dat.dur$arrival,"%d/%m/%Y")
dat.dur$gone<- as.Date(dat.dur$gone,"%d/%m/%Y")
dat.dur$dist<- as.numeric(dat.dur$dist)
str(dat.dur)




corvif(dat.dur[,7:8])
pairs(dat.dur[,7:8])


#### This time model elevation and distance together, they are not correlated (see VIF). Include location in the model and Year

### have a look at differences between years and sites
head(dat.dur)
plot(dat.dur$Year, dat.dur$duration)
plot(dat.dur$area, dat.dur$duration)


hist(dat.dur$dist)
hist(dat.dur$elevation)

### one incorrect data point here, remove it
dat.dur<- subset(dat.dur, dat.dur$elevation<= 9)


```

#GLMM duration
```{r}

dur.mod1b<- glmer.nb(duration ~  area +  tide_strata +
                     +  area:tide_strata + (1|Year), data=dat.dur) 

dur.mod2b<- glmer.nb(duration ~  area +  tide_strata +
                      + (1|Year), data=dat.dur)

AIC(dur.mod1b, dur.mod2b)

dur.mod3b <- glmer.nb(duration ~   tide_strata +
                      
                     (1|Year), data=dat.dur)


AIC(dur.mod2b, dur.mod3b)

dur.mod4b <- glmer.nb(duration ~  1 +
                      
                     (1|Year), data=dat.dur)

AIC(dur.mod3b, dur.mod4b)


```


# durations model plot
```{r}
head(dat.dur)
table(dat.dur$tide_strata, dat.dur$Year)
table(dat.dur$tide_strata, dat.dur$area)


new.dat2<- data.frame(expand.grid('tide_strata'= levels(dat.dur$tide_strata), 'Year'=c('2008','2012') ) )
head(new.dat2)


preds<- predict(dur.mod3b, newdata = new.dat2, type='response')


pred.dat<- cbind( new.dat2, preds)


yr.par= 2008
yr.par2= 2012


### subset for the effect in E.Tarbet and do ech area - plots show "central" trend and the 95% CI from 1000 simulations (fitted with a smoother)
dat8<- subset(pred.dat,  pred.dat$Year==yr.par) ## here we use 2008 to prevent double plotting but it does not matter if its 2008 or 2012 as we are plotting the central tendency
dat12<- subset(pred.dat,  pred.dat$Year==yr.par2)


plot(preds~tide_strata, data=dat8, border='white', ylim=c(5,25), xaxt='n', ylab='Duration (Days)', xlab='Tide stratum')
points(fixed ~dat8$tide_strata, pch=18, cex=3 )

arrows(c(1,2,3,4), dat8$preds, c(1,2,3,4), dat12$preds, length = 0.15, angle = 90, code = 3)

axis(1, at=c(1:4), labels = c('Dry', 'HWS-HWN', 'HWN-LWN', 'LWN-LWS'))




```


